name: scrapy
description: A dart port of the idiomatic python library Scrapy, which provides a fast high-level web crawling & scraping framework for dart and Flutter. 
version: 0.0.3
author: Sacha Arbonel <sacha.arbonel@hotmail.fr>
homepage: https://github.com/Sach97/scrapy.dart
environment:
 sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: ^0.12.0+2
  html: any
